config/routes.rb
Bookmarks::Application.routes.draw do

  resources :users, only: :show

  resources :sessions, only: [:create, :new, :destroy] do
    get 'failure'
  end

  resources :bookmarks do
    resources :comments, except: [:show, :index, :new]
    collection do
      get 'ajax_create'
      get 'search'
      get 'feed'
    end
  end
  get 'tags/:tags' => 'bookmarks#index', :as => :tags
  get '/feed/' => 'bookmarks#feed', defaults: { format: 'atom' }

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  delete '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login

  get "js/bookmarklet(.:format)" => "js#bookmarklet", :as => :bookmarklet

  root :to => 'bookmarks#index'

  

end

app/models/bookmark.rb
require 'uri'
require 'pismo'

class Bookmark
  include Mongoid::Document
  include Mongoid::Taggable
	include Mongoid::Timestamps
  extend Dragonfly::Model

  field :title, type: String
  field :url, type: String
  field :description, type: String
  field :full_text, type: String
  field :favourite, type: Mongoid::Boolean

  field :thumbnail_uid, type: String
  field :thumbnail_name, type: String

  dragonfly_accessor :thumbnail

  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates_presence_of :url
  validates :url, :format => URI::regexp(%w(http https))
  
  after_validation :scrape_info

	scope :favourites, where(favourite: true)
	scope :by_date, (lambda do |date| 
	  dt = DateTime.strptime(date, "%Y-%m-%d")
	  bod = dt.beginning_of_day
	  eod = dt.end_of_day
	  where(:created_at.gte => bod, :created_at.lte => eod)
	end)


  paginates_per 7
  searchkick

  def print_title
    if title.present?
      title
    else
      url
    end
  end

  def user_name
  	if user.present? and user.name.present?
  		user.name
  	else
  		"Anonymous"
  	end
  end

  def search_data
    as_json only: [:title, :description, :tags, :full_text]
  end

  private

  def scrape_info
    if title.blank? || description.blank? || tags.blank?
      doc = Pismo::Document.new(url, :all_images => true)
      self.title = doc.title if title.blank?
      self.description = doc.description || doc.lede if description.blank?
      self.full_text = doc.body
      self.tags = doc.keywords.map {|item| item.first }.join(",") if tags.blank?

      self.thumbnail_url = doc.images.first if doc.images.present? && self.thumbnail.blank?
    end
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  load_and_authorize_resource
  skip_load_and_authorize_resource only: :ajax_create
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :set_menuitem, only: [:index, :new]
  respond_to :js, :html

  # GET /bookmarks
  def index
    @menu_item = "favourites" if params[:favourites]
    query = Bookmark.scoped
    query = query.tagged_with_all(params[:tags]) if params[:tags]
    query = query.by_date(params[:date]) if params[:date]
    query = query.favourites if params[:favourites]
    @bookmarks = query.desc(:created_at).page(params[:page])
    @days = @bookmarks.group_by { |t| t.created_at.beginning_of_day }
  end

  # GET /bookmarks/feed
  def feed
    bookmarks = Bookmark.desc(:created_at)
    @title = "Bookmarks"
    @days = bookmarks.group_by { |t| t.created_at.beginning_of_day } 
    @updated = bookmarks.first.updated_at unless bookmarks.empty?

    respond_to do |format|
      format.atom { render :layout => false }
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end

  end

  # GET /bookmarks/search
  def search
    @bookmarks = Bookmark.search params[:query], page: params[:page]
  end

  # GET /bookmarks/1
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # GET /bookmarks/ajax_create
  def ajax_create
    if session[:user_id]
      begin
        current_user ||= User.find(session[:user_id])
      rescue Mongoid::Errors::DocumentNotFound
        render :json => { "logged_in" => false }.to_json, :callback => params[:callback]
      end

      @bookmark = Bookmark.new(url: params[:url])
      @bookmark.user = current_user

      @bookmark.save
      render :json => @bookmark, :callback => params[:callback]
    else
      render :json => { "logged_in" => false }.to_json, :callback => params[:callback]
    end

  end

  # POST /bookmarks
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.user = current_user

    if @bookmark.save
      redirect_to @bookmark, notice: 'Bookmark was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /bookmarks/1
  def update
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark, notice: 'Bookmark was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /bookmarks/1
  def destroy
    @bookmark.destroy
    redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_menuitem
      @menu_item = params[:action]
    end

    # Only allow a trusted parameter "white list" through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :description, :user, :url, :tags, :favourite)
    end
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
	def comment_link(bookmark)
		if bookmark.comments.empty?
			link_to_unless_current "No Comments", bookmark
		else
			link_to_unless_current pluralize(bookmark.comments.count, "Comment"), bookmark
		end
	end
end

app/views/bookmarks/_bookmark.html.erb
<article>
  <%= image_tag bookmark.thumbnail.thumb('110x75#').url, class: 'thumbnail' if bookmark.thumbnail.present? %>
  <h3><%= link_to bookmark.print_title, bookmark.url %></h3>
  <div><%= bookmark.description %></div>
  <div class="tags"><% bookmark.tags_array.each do |tag| %>
                      <%= link_to "##{tag}", tags_url(:tags => tag) %>
                    <% end %></div>
  <aside class="meta">
    Saved <%= distance_of_time_in_words_to_now(bookmark.created_at) %> ago by <%= user_link(bookmark.user) %> &bullet;
    <%= comment_link(bookmark) %>
    <% if can? :update, bookmark %> &bullet;
      <%= link_to 'Edit', edit_bookmark_path(bookmark) %> &bullet;
      <%= link_to 'Delete', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </aside>
</article>

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
<article>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :favourite %>
    <%= f.check_box :favourite, {}, "true", "false" %>
  </div>
  <div class="actions">
    <%= f.submit "Create Bookmark", class: "button" %>
  </div>
</article>
<% end %>

app/views/bookmarks/edit.html.erb
<%= render 'form' %>

app/views/bookmarks/index.html.erb
<section>
  <% @days.sort.reverse.each do |day, bookmarks| %>
    <h2><%= day.beginning_of_day.strftime("%B %e, %Y") %></h2>
    <% bookmarks.each do |bookmark| %>
      <%= render bookmark %>
    <% end %>    
  <% end %>

  <% if @bookmarks.empty? %>
    <article>
      <p>No bookmarks were found.</p>
    </article>
  <% end %>
</section>
<div>
<%= paginate @bookmarks %>
</div>

app/views/bookmarks/new.html.erb
<%= render 'form' %>

app/views/bookmarks/search.html.erb
<section>
  <h2>Search results</h2>
  <% @bookmarks.each do |bookmark| %>
    <article>
      <h3><%= link_to bookmark.title, bookmark.url %></h3>
      <div><%= bookmark.description %></div>
      <div class="tags"><% bookmark.tags_array.each do |tag| %>
                          <%= link_to "##{tag}", bookmarks_url(:tags => tag) %>
                        <% end %></div>
      <aside class="meta">
        Saved <%= distance_of_time_in_words_to_now(bookmark.created_at) %> ago by <%= bookmark.user_name %> &bullet;
          <%= link_to 'Comments', bookmark %>
        <% if can? :update, bookmark %> &bullet;
          <%= link_to 'Edit', edit_bookmark_path(bookmark) %> &bullet;
          <%= link_to 'Delete', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </aside>
    </article>
  <% end %>
  <% if @bookmarks.empty? %>
    <article>
      <p>No bookmarks were found.</p>
    </article>
  <% end %>
</section>
<div>
<%= paginate @bookmarks %>
</div>

<%= content_for 'section_nav' do %>
  <span><%= link_to 'Latest', bookmarks_path, class: "button active" %></span>
  <span><%= link_to 'Favourites', bookmarks_path, class: "button" %></span>
  <% if can? :new, Bookmark %>
    <span><%= link_to 'New Bookmark', new_bookmark_path, class: "button" %></span>
  <% end %>
<% end %>

app/views/bookmarks/show.html.erb
<%= render @bookmark %>

<section id="comments">
  <h2>Comments</h2>
  <%= render @bookmark.comments %>

  <%= render "comments/form" if can? :create, Comment %>
</section>