config/routes.rb
Bookmarks::Application.routes.draw do

  resources :users, only: :show

  resources :sessions, only: [:create, :new, :destroy] do
    get 'failure'
  end

  resources :bookmarks do
    resources :comments, except: [:show, :index, :new]
    collection do
      get 'ajax_create'
      get 'search'
      get 'feed'
    end
  end
  get 'tags/:tags' => 'bookmarks#index', :as => :tags
  get '/feed/' => 'bookmarks#feed', defaults: { format: 'atom' }

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  delete '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login

  get "js/bookmarklet(.:format)" => "js#bookmarklet", :as => :bookmarklet

  root :to => 'bookmarks#index'

  

end

app/models/comment.rb
class Comment
  include Mongoid::Document
	include Mongoid::Timestamps

  field :body, type: String
  belongs_to :bookmark
  belongs_to :user

  validates_presence_of :body

  def user_name
  	if user.present? and user.name.present?
  		user.name
  	else
  		"Anonymous"
  	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])

    @comment = @bookmark.comments.create(params[:comment].permit(:body))
    @comment.user = current_user

    if @comment.save
      redirect_to @bookmark, notice: 'Comment was successfully posted.'
    else
      redirect_to @bookmark
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @bookmark, notice: 'Comment was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /comments/1
  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @comment = @bookmark.comments.find(params[:id])
    @comment.destroy
    redirect_to @bookmark
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
    @bookmark = Bookmark.find(params[:bookmark_id])
    @comment = @bookmark.comments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:body, :bookmark_id, :user_id)
    end
end

app/views/comments/_comment.html.erb
<article>
	<div><%= raw '&ldquo;' unless current_page?(bookmark_path(comment.bookmark)) %><%= comment.body %><%= raw '&rdquo;' unless current_page?(bookmark_path(comment.bookmark)) %></div>
	<aside class="meta">
		Posted by <%= user_link(comment.user) %> on <%= comment.created_at.strftime("%B %e, %Y") %> <%= 'in ' unless current_page?(bookmark_path(comment.bookmark)) %><%= link_to "#{comment.bookmark.title}", comment.bookmark unless current_page?(bookmark_path(comment.bookmark)) %>
	  <% if can? :update, comment %>
	  	&bullet; <%= link_to 'Delete', [comment.bookmark, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</aside>
</article>

app/views/comments/_form.html.erb
<%= form_for([@bookmark, @bookmark.comments.build]) do |f| %>
  <div>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit "Comment", class: "button" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>