config/routes.rb
Bookmarks::Application.routes.draw do

  resources :users, only: :show

  resources :sessions, only: [:create, :new, :destroy] do
    get 'failure'
  end

  resources :bookmarks do
    resources :comments, except: [:show, :index, :new]
    collection do
      get 'ajax_create'
      get 'search'
      get 'feed'
    end
  end
  get 'tags/:tags' => 'bookmarks#index', :as => :tags
  get '/feed/' => 'bookmarks#feed', defaults: { format: 'atom' }

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  delete '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login

  get "js/bookmarklet(.:format)" => "js#bookmarklet", :as => :bookmarklet

  root :to => 'bookmarks#index'

  

end

app/controllers/js_controller.rb
class JsController < ApplicationController
  layout false

  def bookmarklet
  end
end

app/views/js/bookmarklet.js.erb
(function() {
  function create_container(id) {
    var container = document.createElement("div");
    container.id = id;
    container.innerHTML = "<%= escape_javascript(render( :partial => "shared/ui", :locals => {:api_key => params[:k]}))%>";
    document.body.appendChild(container);
  };

  function save_link() {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "<%= ajax_create_bookmarks_url %>?callback=save_link_complete&url=" + encodeURI(window.location.href);
    script.id = "bookmarks-loadJSONP";
    document.body.appendChild(script);
  }
  
  create_container("bookmarks-container");
  save_link();
})();

function save_link_complete(data) {
  if (data.logged_in == false) {
    set_status("<%= escape_javascript(render("shared/not_logged_in")) %>");
  } else if (data.errors == undefined) {
    set_status("<%= escape_javascript(render("shared/saved")) %>");
  } else {
    set_status("<%= escape_javascript(render("shared/error")) %>");
  }

  var s = document.getElementById("bookmarks-loadJSONP");
  s.parentNode.removeChild(s);

  setTimeout(close_container, 100000);
}

function set_status(content) {
  document.getElementById("bookmarks-status").innerHTML = content;
}

function close_container() {
  var container = document.getElementById('bookmarks-container');
  container.style.display = 'none';
  container.parentNode.removeChild(container);
}