config/routes.rb
Bookmarks::Application.routes.draw do

  resources :users, only: :show

  resources :sessions, only: [:create, :new, :destroy] do
    get 'failure'
  end

  resources :bookmarks do
    resources :comments, except: [:show, :index, :new]
    collection do
      get 'ajax_create'
      get 'search'
      get 'feed'
    end
  end
  get 'tags/:tags' => 'bookmarks#index', :as => :tags
  get '/feed/' => 'bookmarks#feed', defaults: { format: 'atom' }

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  delete '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login

  get "js/bookmarklet(.:format)" => "js#bookmarklet", :as => :bookmarklet

  root :to => 'bookmarks#index'

  

end

app/views/layouts/_navigation.html.erb
<span><%= link_to 'Latest', bookmarks_path, class: "button #{"active" if @menu_item == "index"}", id: "index" %></span>
<span><%= link_to 'Favourites', bookmarks_path(favourites: true), class: "button #{"active" if @menu_item == "favourites"}", id: "favourites" %></span>
<% if can? :new, Bookmark %>
  <span><%= link_to 'New Bookmark', new_bookmark_path, class: "button #{"active" if @menu_item == "new"}", id: "new" %></span>
<% end %>
<span><%= link_to 'Help', page_path("help"), class: "button #{"active" if @menu_item == "help"}", id: "help" %></span>
<% if current_user %>
<span>
    <%= link_to "Logout", logout_path, method: :delete, class: "button secondary" %>
</span>
<% else %>
<span>
    <%= link_to "Login", login_path, class: "button" %>
</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag :atom, "/feed" %>
  <%= auto_discovery_link_tag :rss, "/feed.rss" %>
  <link href='http://fonts.googleapis.com/css?family=Gentium+Book+Basic:400|Open+Sans:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
<header id="top_navigation">
	<nav>
    <% tags.each do |tag| %>
      <span><%= link_to tag, bookmarks_url(:tags => tag) %></span>
    <% end %>
    <%= form_tag search_bookmarks_path, method: :get, class: 'search' do %>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag "Search", name: nil %>
    <% end %>
	</nav>
</header>
<header id="masthead">
<div class="header-content">
  <%= link_to root_path do %>
    <h1>Bookmarks</h1>
  <% end %>
  <nav>
    <%= render "layouts/navigation" %>
  </nav>
</div>
</header>
<div class="main">
  <section>
  <% if notice %><p id="notice"><%= notice %></p><% end %>
  <%= yield %>
  </section>
</div>
</body>
</html>